// Turns the human-authored `themes/*.yaml` files into the artifacts the app and
// editors consume. Runs automatically before every build (`prebuild`) and on
// demand via `pnpm run gen:themes`. Its outputs are committed (like
// libcard.schema.json) so `astro dev` and the gallery work without a build step.
//
// Emits:
//   • src/styles/themes.gen.css   one [data-theme] block per theme (the only
//                                 place theme tokens become CSS)
//   • src/data/themes.json        the registry: slug, name, author, license, …
//   • themes/theme.schema.json    JSON Schema for themes/*.yaml editor autocomplete
//   • themes/README.md            refreshes the theme table between <!--THEMES--> markers
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { zodToJsonSchema } from "zod-to-json-schema";
import { loadThemes, toRegistryEntry, themeToCss, themeSchema, TOKEN_CONTRACT } from "../src/lib/theme-schema.mjs";

const root = new URL("../", import.meta.url);
const themesDir = fileURLToPath(new URL("themes", root));

let all;
try {
  all = loadThemes(themesDir);
} catch (err) {
  // A bad theme should fail the build/PR with a clean, readable message — not a
  // stack trace. (loadThemes throws "Invalid theme … : • field: message".)
  console.error("\n✗ " + (err?.message ?? err) + "\n");
  process.exit(1);
}
const shipped = all.filter((t) => !t.isExample);

// 1) Generated CSS — one scoped block per shipped theme.
const css =
  "/* GENERATED by scripts/gen-themes.mjs — DO NOT EDIT.\n" +
  "   Edit the source themes in themes/*.yaml and run `pnpm run gen:themes`. */\n\n" +
  shipped.map(themeToCss).join("\n\n") +
  "\n";
writeFileSync(new URL("src/styles/themes.gen.css", root), css);

// 2) Registry — compact, serializable, drives the switcher + gallery + setup.
const registry = shipped.map(toRegistryEntry);
mkdirSync(new URL("src/data/", root), { recursive: true });
writeFileSync(new URL("src/data/themes.json", root), JSON.stringify(registry, null, 2) + "\n");

// 3) JSON Schema for themes/*.yaml (editor autocomplete + the CI validate step).
const jsonSchema = zodToJsonSchema(themeSchema, { name: "LibcardTheme", $refStrategy: "none" });
writeFileSync(new URL("themes/theme.schema.json", root), JSON.stringify(jsonSchema, null, 2) + "\n");

// 4) Refresh the README theme table (only between the markers, if present).
const readmeUrl = new URL("themes/README.md", root);
if (existsSync(readmeUrl)) {
  const md = readFileSync(readmeUrl, "utf-8");
  const start = "<!-- THEMES:START -->";
  const end = "<!-- THEMES:END -->";
  if (md.includes(start) && md.includes(end)) {
    const rows = shipped
      .map((t) => {
        const by = t.authorUrl ? `[${t.author}](${t.authorUrl})` : t.author;
        const badge = t.official ? "✅" : "";
        return `| **${t.name}** (\`${t.slug}\`) | ${t.mode} | ${by} | ${t.license} | ${badge} |`;
      })
      .join("\n");
    const table =
      "| Theme | Mode | Author | License | Built-in |\n" +
      "|---|---|---|---|---|\n" +
      rows;
    const next = md.replace(
      new RegExp(`${start}[\\s\\S]*${end}`),
      `${start}\n\n${table}\n\n${end}`,
    );
    writeFileSync(readmeUrl, next);
  }
}

const tokenCount = TOKEN_CONTRACT.length;
console.log(
  `✓ Generated ${shipped.length} themes (${tokenCount}-token contract) → themes.gen.css, themes.json, theme.schema.json`,
);
