// LibCard setup wizard — `pnpm run setup`.
//
// A zero-dependency (Node builtins + the `yaml` package) interactive prompt that
// fills in libcard.config.yaml for you, including the easy-to-get-wrong
// site.url / site.base values, which it derives from your git remote.
//
// NOTE: invoke as `pnpm run setup`, never `pnpm setup` (the latter is pnpm's own
// built-in command for configuring its shell environment).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createInterface } from "node:readline/promises";
import { execSync } from "node:child_process";
import { stdin, stdout } from "node:process";
import { parse, stringify } from "yaml";
import { THEMES } from "../src/lib/schema.mjs";

const CONFIG_PATH = new URL("../libcard.config.yaml", import.meta.url);

const rl = createInterface({ input: stdin, output: stdout });

/** Prompt with an optional default shown in brackets. */
async function ask(question, fallback = "") {
  const suffix = fallback ? ` [${fallback}]` : "";
  const answer = (await rl.question(`${question}${suffix}: `)).trim();
  return answer || fallback;
}

/** Best-effort guess of GitHub Pages url/base from `git remote get-url origin`. */
function deriveSite() {
  try {
    const remote = execSync("git remote get-url origin", { encoding: "utf-8" }).trim();
    const match = remote.match(/github\.com[:/]([^/]+)\/(.+?)(?:\.git)?$/i);
    if (!match) return { url: "", base: "/" };
    const [, owner, repo] = match;
    const isUserSite = repo.toLowerCase() === `${owner.toLowerCase()}.github.io`;
    return {
      url: `https://${owner.toLowerCase()}.github.io`,
      base: isUserSite ? "/" : `/${repo}`,
    };
  } catch {
    return { url: "", base: "/" };
  }
}

async function main() {
  const existing = existsSync(CONFIG_PATH) ? parse(readFileSync(CONFIG_PATH, "utf-8")) ?? {} : {};
  const guessed = deriveSite();

  console.log("\n  LibCard setup — press Enter to keep the value in [brackets].\n");

  const profile = existing.profile ?? {};
  const contact = existing.contact ?? {};
  const seo = existing.seo ?? {};
  const site = existing.site ?? {};

  const name = await ask("Your name", profile.name ?? "");
  const tagline = await ask("Tagline", profile.tagline ?? "");
  const avatar = await ask("Avatar (a /public path or https URL)", profile.avatar ?? "/avatar.svg");
  const location = await ask("Location", profile.location ?? "");

  const email = await ask("Contact email", contact.email ?? "");
  const phone = await ask("Phone", contact.phone ?? "");
  const organization = await ask("Organization", contact.organization ?? "");
  const title = await ask("Job title", contact.title ?? "");
  const website = await ask("Website", contact.website ?? "");

  // `theme` may be a bare slug or the object (switcher) form — read the name.
  const currentTheme = typeof existing.theme === "string" ? existing.theme : (existing.theme?.name ?? "default");
  const theme = await ask(`Theme (${THEMES.join(" | ")})`, currentTheme);
  const description = await ask("SEO description", seo.description ?? tagline);

  const siteUrl = await ask("GitHub Pages URL", site.url ?? guessed.url);
  const siteBase = await ask("Base path", site.base ?? guessed.base);

  console.log("\n  Add your links. Leave the label blank to finish.\n");
  const links = [];
  // Keep existing links unless the user wants to start fresh.
  if (Array.isArray(existing.links) && existing.links.length) {
    const keep = (await ask(`Keep your ${existing.links.length} existing link(s)? (y/n)`, "y")).toLowerCase();
    if (keep.startsWith("y")) links.push(...existing.links);
  }
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const label = await ask("  Link label (blank to stop)");
    if (!label) break;
    const url = await ask("  Link URL");
    const icon = await ask("  Icon name (optional, e.g. github, globe)");
    const link = { label, url };
    if (icon) link.icon = icon;
    links.push(link);
  }

  const socials = Array.isArray(existing.socials) ? existing.socials : [];

  // Keep the switcher settings if the user already had the object form.
  const chosen = THEMES.includes(theme) ? theme : "default";
  const themeOut =
    existing.theme && typeof existing.theme === "object" ? { ...existing.theme, name: chosen } : chosen;

  const config = {
    profile: clean({ name, tagline, avatar, location }),
    contact: clean({ email, phone, organization, title, website }),
    links,
    socials,
    theme: themeOut,
    seo: clean({ description }),
    site: { url: siteUrl, base: siteBase || "/" },
  };

  const header =
    "# yaml-language-server: $schema=./libcard.schema.json\n" +
    "#\n# Generated by `pnpm run setup`. Edit freely — your editor will\n" +
    "# autocomplete and validate against the schema referenced above.\n\n";

  writeFileSync(CONFIG_PATH, header + stringify(config));
  console.log("\n  ✓ Wrote libcard.config.yaml");
  console.log("  Next: pnpm dev   (preview)   ·   git push   (deploy)\n");
}

/** Drop empty-string / undefined keys so the YAML stays tidy. */
function clean(obj) {
  return Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== "" && v != null));
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => rl.close());
